### ISSUE TITLE
Patch the VERSIONS build arg to set in the hyperkube buildconfig

### ISSUE THREAD

**Issue by aleskandro** [okd-project/okd-payload-pipeline#53]
```yaml
        - name: VERSIONS
          value: "kubernetes=1.25.0"
          # TODO ^^ dynamic handling from the pipeline

```

https://github.com/okd-project/okd-payload-pipeline/blob/aeeb5410022115a073f0412337051b8514a2605a/buildconfigs/10-hyperkube.yaml
